train_path: "./data/train_values.csv"
label_path: "./data/train_labels.csv"
test_path: "./data/test_values.csv"
prediction_cat:
  encoder_path: "./productionModels/geo_embed.h5"
  one_hot_geo_path: "./productionModels/one_hot_geo.joblib"
  model_type: "catboost"
  model_path: "./productionModels/catboost_fold1.cbm"
  one_hot_cols:
    [
      "count_floors_pre_eq",
      "age",
      "area_percentage",
      "height_percentage",
      "has_superstructure_adobe_mud",
      "has_superstructure_mud_mortar_stone",
      "has_superstructure_stone_flag",
      "has_superstructure_cement_mortar_stone",
      "has_superstructure_mud_mortar_brick",
      "has_superstructure_cement_mortar_brick",
      "has_superstructure_timber",
      "has_superstructure_bamboo",
      "has_superstructure_rc_non_engineered",
      "has_superstructure_rc_engineered",
      "has_superstructure_other",
      "count_families",
      "has_secondary_use",
      "has_secondary_use_agriculture",
      "has_secondary_use_hotel",
      "has_secondary_use_rental",
      "has_secondary_use_institution",
      "has_secondary_use_school",
      "has_secondary_use_industry",
      "has_secondary_use_health_post",
      "has_secondary_use_gov_office",
      "has_secondary_use_use_police",
      "has_secondary_use_other",
      "land_surface_condition_n",
      "land_surface_condition_o",
      "land_surface_condition_t",
      "foundation_type_h",
      "foundation_type_i",
      "foundation_type_r",
      "foundation_type_u",
      "foundation_type_w",
      "roof_type_n",
      "roof_type_q",
      "roof_type_x",
      "ground_floor_type_f",
      "ground_floor_type_m",
      "ground_floor_type_v",
      "ground_floor_type_x",
      "ground_floor_type_z",
      "other_floor_type_j",
      "other_floor_type_q",
      "other_floor_type_s",
      "other_floor_type_x",
      "position_j",
      "position_o",
      "position_s",
      "position_t",
      "plan_configuration_a",
      "plan_configuration_c",
      "plan_configuration_d",
      "plan_configuration_f",
      "plan_configuration_m",
      "plan_configuration_n",
      "plan_configuration_o",
      "plan_configuration_q",
      "plan_configuration_s",
      "plan_configuration_u",
      "legal_ownership_status_a",
      "legal_ownership_status_r",
      "legal_ownership_status_v",
      "legal_ownership_status_w",
    ]

prediction_lgb:
  encoder_path: "./productionModels/geo_embed.h5"
  one_hot_geo_path: "./productionModels/one_hot_geo.joblib"
  model_type: "lightgbm"
  model_path: "./productionModels/model0.txt"
  one_hot_cols:
    [
      "count_floors_pre_eq",
      "age",
      "area_percentage",
      "height_percentage",
      "has_superstructure_adobe_mud",
      "has_superstructure_mud_mortar_stone",
      "has_superstructure_stone_flag",
      "has_superstructure_cement_mortar_stone",
      "has_superstructure_mud_mortar_brick",
      "has_superstructure_cement_mortar_brick",
      "has_superstructure_timber",
      "has_superstructure_bamboo",
      "has_superstructure_rc_non_engineered",
      "has_superstructure_rc_engineered",
      "has_superstructure_other",
      "count_families",
      "has_secondary_use",
      "has_secondary_use_agriculture",
      "has_secondary_use_hotel",
      "has_secondary_use_rental",
      "has_secondary_use_institution",
      "has_secondary_use_school",
      "has_secondary_use_industry",
      "has_secondary_use_health_post",
      "has_secondary_use_gov_office",
      "has_secondary_use_use_police",
      "has_secondary_use_other",
      "land_surface_condition_n",
      "land_surface_condition_o",
      "land_surface_condition_t",
      "foundation_type_h",
      "foundation_type_i",
      "foundation_type_r",
      "foundation_type_u",
      "foundation_type_w",
      "roof_type_n",
      "roof_type_q",
      "roof_type_x",
      "ground_floor_type_f",
      "ground_floor_type_m",
      "ground_floor_type_v",
      "ground_floor_type_x",
      "ground_floor_type_z",
      "other_floor_type_j",
      "other_floor_type_q",
      "other_floor_type_s",
      "other_floor_type_x",
      "position_j",
      "position_o",
      "position_s",
      "position_t",
      "plan_configuration_a",
      "plan_configuration_c",
      "plan_configuration_d",
      "plan_configuration_f",
      "plan_configuration_m",
      "plan_configuration_n",
      "plan_configuration_o",
      "plan_configuration_q",
      "plan_configuration_s",
      "plan_configuration_u",
      "legal_ownership_status_a",
      "legal_ownership_status_r",
      "legal_ownership_status_v",
      "legal_ownership_status_w",
    ]
